// ============================================================================
//  shader_data.c — Embed precompiled shader bytecode as linkable symbols.
//  These .inc files are generated by the CMake build (fxc/dxc → binary → xxd).
//  The ASM main.asm references these as extern symbols.
// ============================================================================

#include <stdint.h>

// Symbols referenced by main.asm
#ifdef __cplusplus
extern "C" {
#endif

const uint8_t  g_vsBlob[]    = {
#include "generated_vs.inc"
};
const uint32_t g_vsBlobSize   = sizeof(g_vsBlob);

const uint8_t  g_psBlob[]    = {
#include "generated_ps.inc"
};
const uint32_t g_psBlobSize   = sizeof(g_psBlob);

#ifdef __cplusplus
}
#endif
